### ISSUE TITLE
Separate tutorial sections

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#103]
The tutorials will be grouped into three categories - beginner, advanced and cookbook. Currently, the dojo.io site doesn't have anyway to delineate these categories which could make it difficult for visitors to find what they are looking for.

**Comment by dylans** [comment]
I agree we need categories, though I'm not 100% sold on the 3 category choices. For example, perhaps something like introduction or getting started for the initial sequential series, and then cookbook for everything else. Does advanced follow a story arc, or are those somewhat independent as well?

**Comment by vansimke** [comment]
I agree that the proposed names aren't necessarily the best, we can iterate on those.

The plan is for the advanced to relate to the demo app, but they will be independent since the learner might want to go through the material along different paths.
