### ISSUE TITLE
Create tutorial on using the widget registry

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#104]
This tutorial will show the user how to pre-register widgets using the registry object from @dojo/widget-core/d

**Comment by agubler** [comment]
This will want to talk about registries that are available for consumers, how to add to the registry, how to set a projector registry, the use cases for using the registry like lazy loading, swapping implementation etc etc

**Comment by agubler** [comment]
@matt-gadd and I will be working on this one together... @vansimke @dylans is this another tutorial that needs to use the biz-e-bodies theme? Or can this be a separate decoupled tutorial?

**Comment by dylans** [comment]
@agubler At a minimum it can be decoupled in that it doesn't need to be cumulative with the first 6 tutorials. If the Biz-e-bodies concept isn't good for this one, then go another direction. Or feel free to use the concept without having to build on any earlier code.
