### ISSUE TITLE
Create "The vDOM abstractions: d, w, and v" article

### ISSUE THREAD

**Issue by eheasley** [dojo/dojo.io#11]
This article will discuss the three vDOM abstraction functions and how they relate to each other and the underlying “h” function. This section should discuss how Dojo 2 uses HyperScript, but should not get into too much detail on that. Links to HyperScript documentation should be provided, if needed.

**Comment by morrinene** [comment]
@agubler 

Provide the following so an article can be drafted that provides more detailed background information about key features of VDOM abstractions and key concepts and patterns for being effective in working with it in Dojo 2:

- Summary of key points that a user should know about the topic
- Code examples (or links to relevant existing examples)
- Links to relevant reference material

**Comment by agubler** [comment]
I wonder how different this would be from the widget bible stuff @kitsonk has been doing? Which covers the `v` and `w` abstractions?

**Comment by kitsonk** [comment]
Agreed.  There is a huge amount of duplication with #110.

**Comment by morrinene** [comment]
We'll base the reference guide off of the output from #110.  We'll describe the parts related directly to d, w, and v and then link to the bible.  Moving this back into To Do

**Comment by pottedmeat** [comment]
What I have so far: https://github.com/pottedmeat/dojo.io/blob/11-dwv/site/source/tutorials/vdom_abstractions.md
