### ISSUE TITLE
Create article for Development Environment

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#112]
This article is intended to present a learner with a step-by-step guide for how to setup a local development environment for developing Dojo2 applications. This should include all packages that need to be installed as well as a brief explanation on how each of them is used. Ideally, the learner would be taken through the process of going from an empty directory to having a full-featured environment capable of compilation, deployment, testing, etc. Additionally, instructions on how to setup TypeScript for some of the common editors (Vim, VS Code, Atom, …) should be linked to.

**Comment by morrinene** [comment]
Provide the following so an article can be drafted that provides more detailed background information about key features of Accessibility and key concepts and patterns for being effective in working with it in Dojo 2:

- Summary of key points that a user should know about the topic
- Code examples (or links to relevant existing examples)
- Links to relevant reference material

**Comment by kitsonk** [comment]
The draft article is available [here](https://github.com/dojo/dojo.io/compare/master...kitsonk:development-environment) as a diff or can be viewed [here](https://github.com/kitsonk/dojo.io/blob/a40bbe34318573db78ffcb0925e54615a7f2faf8/site/source/tutorials/901_development_environment/index.md) rendered by GitHub.

**Comment by morrinene** [comment]
PR merged, we're done!
