### ISSUE TITLE
Create tutorial for Theming

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#113]

**Comment by tomdye** [comment]
For this tutorial I intend to show how to write and apply a theme to the biz-e-bodies application.
I will start with the output from tutorial 5 and guide the user through the required steps for styling.
The output will be a theme that can be toggled on / off using a checkbox. 
I will require input from Scott to come up with an attractive looking theme.

## Tutorial steps:
* Introduce themes and how they work
* Change top level classes for each element to `root` as per best practice
* Create theme directory and structure
* Create simple theme file for worker
* Use theme injector to pass theme to app
* Add toggle for theme on / off
* Complete theme for app using shared variables

@vansimke @dylans thoughts please?

**Comment by vansimke** [comment]
@tomdye this looks really good to me.
