### ISSUE TITLE
Create tutorial for State containers

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#114]

**Comment by morrinene** [comment]
Outline the following items for the creation of this tutorial, or add notes on where we should put it!

- Summary of key points about what we are teaching in this tutorial
- Takeaways from the Tutorial
- High-level outline of steps for Tutorial
- Initial and final version of the code
- Code examples (or links to relevant existing examples)
- Links to any relevant reference material

**Comment by agubler** [comment]
@dylans @vansimke @kitsonk what is the current status of #145? Those are the words that were written to accompany the state tutorial skeleton I put together?

**Comment by dylans** [comment]
@agubler I assume you got the answer you needed, but if not, just ask me tomorrow

**Comment by agubler** [comment]
Completed via #172
