### ISSUE TITLE
Create tutorial for Advanced property passing

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#115]

**Comment by morrinene** [comment]
Outline the following items for the creation of this tutorial:

- Summary of key points about what we are teaching in this tutorial
- Takeaways from the Tutorial
- High-level outline of steps for Tutorial
- Initial and final version of the code
- Code examples (or links to relevant existing examples)
- Links to any relevant reference material

**Comment by morrinene** [comment]
@dylan 

The original intent of this article may have been related to injecting properties using the injector. However, this may be covered by state, as it goes hand in hand with the container/injector combo.  

Can you provide a description for this tutorial?  If we don't need it anymore or if it's covered by the state tutorial, let's close it.

**Comment by dylans** [comment]
let's get the state one done and then see if we feel there is more that is needed here. Given that I say we push this to beta3

**Comment by dylans** [comment]
I think this is covered by other tutorials.
