### ISSUE TITLE
Your first Dojo 2 application - Tutorial Tests

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#133]
Please create tests for the examples in Tutorial 001: Your first Dojo 2 application

> One of the biggest issues with examples on dojotoolkit.org was that new releases of dojo or new releases of browsers would leave examples broken. Without a way to monitor or identify these issues, we could only hope that a user would report the issue sooner, rather than later.
> 
> For dojo.io, examples should include unit tests and be structured in a way that automatically verifies that the example works with the latest version of dojo, or if it is deprecated any only works with the libraries used in the example.

**Comment by jacobroufa** [comment]
PR submitted at #137. For some reason it's telling me I've not signed the JSF CLA... I'm not sure why, as I definitely have signed it. Let me know if there's anything else I need to do for this issue. Thanks!

**Comment by jacobroufa** [comment]
Nevermind the comment about the JSF CLA... the `grunt webserv` command apparently changed the email address in my `~/.gitconfig`!! Changed it back and amended the commit, then I force pushed. PR now says that CLA has been signed, as it should be. Cheers!
