### ISSUE TITLE
Creating widgets - Tutorial Tests

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#134]
Please create tests for the examples in Tutorial 003: Creating widgets

> One of the biggest issues with examples on dojotoolkit.org was that new releases of dojo or new releases of browsers would leave examples broken. Without a way to monitor or identify these issues, we could only hope that a user would report the issue sooner, rather than later.
> 
> For dojo.io, examples should include unit tests and be structured in a way that automatically verifies that the example works with the latest version of dojo, or if it is deprecated any only works with the libraries used in the example.

**Comment by edhager** [comment]
My work in progress is here: https://github.com/edhager/dojo.io/tree/unit-tests

**Comment by edhager** [comment]
I misunderstood the goal of this ticket.  I started modifying the dojo.io grunt scripts to compile the tutorial code and run dojo.io unit tests on those tutorials.  After talking to @maier49, I realized his goal was to install, compile and test each tutorial as the users would do it.  My work will be in this branch: https://github.com/edhager/dojo.io/tree/tutorial-build-tests
