### ISSUE TITLE
Create "Reactive Programming" article

### ISSUE THREAD

**Issue by eheasley** [dojo/dojo.io#14]
This document will focus on the concept of reactive programming and how it differs from traditional techniques. It should outline what reactive programming is and the advantages that this technique has when applied to front-end development.

**Comment by morrinene** [comment]
Hi @rishson 

Provide the following so an article can be drafted that provides more detailed background information about Reactive Programming and key concepts and patterns for being effective in working with it in Dojo 2:

- Summary of key points that a user should know about the topic
- Code examples (or links to relevant existing examples)
- Links to relevant reference material
