### ISSUE TITLE
View for tutorials is a bit restricted

### ISSUE THREAD

**Issue by agubler** [dojo/dojo.io#144]
The new tutorial layout is great, but the actual container for the tutorial itself is a bit restricted by the size header and footer so not much content can be see.

It would be even better if the tutorial view could be increased in some way.

**Comment by vansimke** [comment]
@agubler I believe that PR #342 resolves the concerns raised in this issue. Do you agree or is there more to do here?

**Comment by agubler** [comment]
@vansimke Yeah I think so.
