### ISSUE TITLE
Urgent: Bug in Safari, Tutorial not visible

### ISSUE THREAD

**Issue by sebilasse** [dojo/dojo.io#148]
see e.g. https://dojo.io/tutorials/004_user_interactions/ with Safari 10.1.2 :

The tutorial is not visible. `div.scrollable` has no height and so the site looks "blank"

<img width="1209" alt="bildschirmfoto 2017-07-05 um 08 06 47" src="https://user-images.githubusercontent.com/750300/27851106-085bfe4a-6159-11e7-9951-ce6670a8f029.png">

**Comment by kitsonk** [comment]
Checked with Safari 11 and the issue is no present, still present on Safari 9.1 and 10.1.
