### ISSUE TITLE
Create article or tutorial on validating user input

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo.io#152]
A common use case is validating user input.  We should demonstrate how best to do that with Dojo 2 for common use cases.

**Comment by agubler** [comment]
Do we have a preferred pattern for this in widgets? I'm not sure I am the best person to write this particular tutorial/article...

**Comment by kitsonk** [comment]
I suspect we need to have a preferred pattern...  It isn't a use case we would want to have [open ended](https://stackoverflow.com/questions/24019431/how-to-properly-validate-input-values-with-react-js) as that feels anti-pattern for Dojo 2 to just shrug our shoulders and say _we don't care_.

If you aren't the right person, who on our team would be?

**Comment by agubler** [comment]
I don't disagree, we should certainly have a recommended approach for validating user input. I wasn't sure if we actually had one already? One that had been worked out through creating our widget library?

I was thinking that one of the widget guys would perhaps be in a better place (at least if it's something that has already had some thought)

**Comment by dylans** [comment]
let's see if @tomdye @bitpshr or @smhigley have any thoughts on this... if we don't have an established pattern now then we should push this beyond this week.

**Comment by smhigley** [comment]
Form widgets all have `invalid` as one of the properties, and setting it to `true` or `false` updates state classes and aria attributes. In widget examples thus far, validation has happened in either the `onChange` or `onBlur` callback.

I remember adding some validation to the form tutorial, but I think it was eventually taken out. @agubler would you be interested in trading this article (or tutorial?) for the developer tools one: #107? I don't think I'm the right person for that one :P

**Comment by kitsonk** [comment]
There is the reflecting the invalid state of a widget, which we have an agreement on, but I can see at least a few use cases where we need to have the _Dojo 2 way_:

* Validation on intermediate values, like when when entering in a credit card number, where there could be validation before the `onblur` occurs, or looking up values in a drop down list.
* Validation after `onblur` before there is a _commit_, where validation is against a _model_ but before a transition is _comitted_.
* Rejection of information once a transaction is _committed_.

The interaction of the widgets with the application state (state container) is fairly important.  While the tutorial needs to embodies these patterns, I don't think we have it clear how we achieve those patterns that are agreed.
