### ISSUE TITLE
Create Tutorial for Routing

### ISSUE THREAD

**Issue by dylans** [dojo/dojo.io#171]
Tutorial to show off the benefits and usage of @dojo/routing.

**Comment by agubler** [comment]
I assumed that I would be doing the routing tutorial? Does @devpaul mind if I take it?

**Comment by devpaul** [comment]
I haven't started yet. If you have something already you're welcome to it 👍

**Comment by agubler** [comment]
Plan for routing tutorial:

1) Add `Home.ts`,  with it just "Welcome To Biz-E-Bodies"
2) Add side menu, with links for `home`, `worker directory` and `new worker`
3) In Worker Directory add A-Z filter links that will filter the workers based on surname.
