### ISSUE TITLE
Tutorial navigation buttons take me to an empty screen

### ISSUE THREAD

**Issue by edhager** [dojo/dojo.io#181]
I am using the latest version of Chrome.

Follow these steps to reproduce:
- Go to a tutorial that has multiple pages.  For example: https://dojo.io/tutorials/002_creating_an_application/
- Navigate to the second to last page.
- Double click or click on the "Next" button rapidly.

I end up on a page with the title bar, no content and a "Begin tutorial" button.  The router is going to page #0: https://dojo.io/tutorials/002_creating_an_application/#0.

**Comment by edhager** [comment]
![tutorial-navigation-bug](https://user-images.githubusercontent.com/4441986/30499050-db1c5ebe-9a0d-11e7-8c2d-0afbf887db63.gif)

**Comment by dylans** [comment]
Both @agubler and I observed this bug this week as well. Thanks for tracking down how to reproduce it @edhager!

**Comment by dylans** [comment]
Note moving to previous next seems to not adjust scrolling back to the top of a tutorial either.

**Comment by agubler** [comment]
Resolved.
