### ISSUE TITLE
Tutorial> State management> page 1 > Cannot find module

### ISSUE THREAD

**Issue by bwakkie** [dojo/dojo.io#193]
It was not so clear for me when to run dojo build -w so I did this after every page till it succeeded. When it did (near the end) the following error occurred:
ERROR in /var/www/dojo/1010_containers_and_injecting_state/initial/biz-e-corp/src/widgets/ApplicationContext.ts                                  
(4,34): error TS2307: Cannot find module './widgets/Worker'.
                                                                                                 
ERROR in /var/www/dojo/1010_containers_and_injecting_state/initial/biz-e-corp/src/widgets/ApplicationContext.ts                                                                                   
(5,32): error TS2307: Cannot find module './widgets/WorkerForm'.

I had to change ./ into ./../ and it worked. This should be fixed on the first page.

**Comment by dylans** [comment]
Hi @bwakkie, I'm trying to make sure I understand this issue.

Are you suggesting that from within ApplicationContext.ts, that:

```
import { WorkerProperties } from './widgets/Worker';
import { WorkerFormData } from './widgets/WorkerForm';
```

should be

```
import { WorkerProperties } from './../widgets/Worker';
import { WorkerFormData } from './../widgets/WorkerForm';
```

If so, it's not clear to me why that would be the case as the file hierarchy is:

```
src/
src/ApplicationContext.ts
src/widgets/Worker.ts
src/widgets/WorkerForm.ts
```

As far as running dojo build -w, you can do this throughout, but of course it won't compile correctly until enough of the demo is in a working state.

From which directory are you running `dojo build -w`?

**Comment by bwakkie** [comment]
Hi @dylans,  I start dojo build -w from within the root folder /biz-e-corp/ after doing the npm install but nowhere in this tutorial both commands are mentioned. So I was confused.

Anyway I discovered my problem, I had in both the src and the widget dir an ApplicationContext.ts and i was referring to the one in the widget dir which isn't supposed to be there. So close call. Sorry.

**Comment by dylans** [comment]
Thanks @bwakkie 

In the opening of the state management tutorial, we say this:

Prerequisites

This tutorial assumes that you have gone through the beginner tutorial series. (which them links to the series where we cover `dojo build -w`, etc.

Let me know if you think that is too subtle, and if we should remind the reader of these commands. It's really helpful to get feedback on the first time experience. Thanks!
