### ISSUE TITLE
Zip tutorial demos during deployment

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#2]
When dojo.io is deployed, all of the demo projects that support the tutorials need to be zipped up and made available to be downloaded from the dojo.io site.

**Comment by vansimke** [comment]
Need to take each demo and package them to be downloaded. Each tutorial should be zipped with a name that starts with the tutorial name followed by either "initial" or "finished". For example, the initial demo for the first tutorial would be called "001_static_content-initial.zip". These files should be accessible from the tutorials folder within the site with a URL scheme like: `https://dojo.io/tutorials/assets/001_static_content-initial.zip`.

**Comment by devpaul** [comment]
Resolved by #3.

Run `grunt tutorials` to create a zip of the tutorials.
