### ISSUE TITLE
a11y Best Practices

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo.io#207]
@kitsonk commented on [Wed Nov 16 2016](https://github.com/dojo/widget-core/issues/106)

# User Story

Developers of Dojo 2 should have clear guidance on how to make their applications accessible and how best to ensure their applications are accessible.

# Solution

Most of the best practices will be for custom widget authors, which is guidance about how best to ensure their widgets will behave will when integrated into an application and that the DOM a widget generates is accessible.

---

@dylans commented on [Fri Apr 21 2017](https://github.com/dojo/widget-core/issues/106#issuecomment-296168404)

We may want to consider the [`prefers-reduced-motion` media query](https://github.com/w3c/csswg-drafts/issues/442) somewhere in our approach for a11y. Browser support is in Safari 10.1, iOS 10.3, and perhaps others. https://css-tricks.com/introduction-reduced-motion-media-query/ has a decent summary.

There are also plans to add [CSS media query settings for contrast and transparency](https://github.com/w3c/csswg-drafts/issues/443).

---

@smhigley commented on [Fri Apr 21 2017](https://github.com/dojo/widget-core/issues/106#issuecomment-296220667)

@dylans I like it! I think it would be nice to provide, with a caveat saying "we still recommend you make all your animations accessibility-friendly." Should we provide alternate styles for that and high contrast in themes based on a property that adds a class to the projector?

---

@rishson commented on [Fri Apr 21 2017](https://github.com/dojo/widget-core/issues/106#issuecomment-296221575)

High-contrast theme would be really useful (as long as it doesn't clash with a user putting their OS in high contrast mode) - is that what you were suggesting?

---

@smhigley commented on [Fri Apr 21 2017](https://github.com/dojo/widget-core/issues/106#issuecomment-296222778)

@rishson yeah, I did mean a separate high-contrast theme. Morning brain :). More contrast-y styles won't conflict with OS high contrast mode.

---

@dylans commented on [Fri Apr 21 2017](https://github.com/dojo/widget-core/issues/106#issuecomment-296238848)

Also, should we publish the aria guidelines from our Google doc as part of the meta perhaps (either as a wiki or a document), or plan to have them as part of the reference guide?

**Comment by smhigley** [comment]
@kitsonk are there any direct actions that need to be done to address this? We already have the accessibility article for now: https://dojo.io/tutorials/accessibility

**Comment by kitsonk** [comment]
@smhigley if you feel all the feedback from the copied issue has been covered this issue can be closed.  I just moved the issue because it was referring to information we should make available on dojo.io.  Since we still don't have the ability to publish reference guide materials, I suspect there is more information we would want to publish about that, in particular @dylans last comment.

**Comment by dylans** [comment]
This content is live on the reference guide, closing out the issue.
