### ISSUE TITLE
Add explanation of why the projector is called a "projector" to 2nd tutorial 

### ISSUE THREAD

**Issue by eheasley** [dojo/dojo.io#23]
@dylans commented:

> At some point I'd like an aside that explains why it's called a projector (especially for Germans where a projector is called a beamer)... let's open a separate issue to add an aside explaining the term, or to make sure we later cover it in the virtual dom article.

**Comment by vansimke** [comment]
depends on [Issue 33](https://github.com/dojo/dojo.io/issues/33)

**Comment by vansimke** [comment]
Closed via #97
