### ISSUE TITLE
Tutorial feedback - Creating widgets

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#230]
Link: https://dojo.io/tutorials/003_creating_widgets/#7

> The application now renders three workers in the WorkerContainer widget, allowing us to control how they are laid out without impacting the overall application.

Would be nice to see a screenshot of what the app should look like at this point.

**Comment by kitsonk** [comment]
Duplicate of #266

Let's keep this one comment as a single concept/idea.
