### ISSUE TITLE
Tutorial 1060 - invalid link

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#231]
Link: https://dojo.io/tutorials/1060_data_driven_widgets/

Step 0: “You can download the demo project”

(https://dojo.io/tutorials/assets/006_data_driven_widgets-initial.zip) Links to a 404. Looks like the correct URL is: https://dojo.io/tutorials/assets/1060_data_driven_widgets-initial.zip

**Comment by kitsonk** [comment]
If you find stuff like this it would be really valuable to just raise a PR as well.
