### ISSUE TITLE
Going to the https URL shows privacy error

### ISSUE THREAD

**Issue by nicknisi** [dojo/dojo.io#24]
Going to https://dojo.io shows a privacy error.

![screen shot 2017-03-28 at 4 16 21 pm](https://cloud.githubusercontent.com/assets/293805/24428498/4b3dfdee-13d4-11e7-858a-a67b54f108bb.png)

**Comment by agubler** [comment]
Should perhaps also auto forward from `http` to `https` once sorted.

**Comment by devpaul** [comment]
GitHub pages doesn't support https for custom URLs

**Comment by dylans** [comment]
One option is to put dojo.io under cloudflare (basically the CDN service used by the foundation), if that's the only limit we have. Are there other issues we currently have that we don't like or that are going to cause us issues, e.g. #57?

**Comment by devpaul** [comment]
CloudFlare looks like a reasonable solution. Relevant blog is here: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by devpaul** [comment]
@dylans can you get me information necessary to use CloudFlare?

**Comment by dylans** [comment]
@devpaul I'm currently in the process of getting dojo.io transferred from my personal registrar account to the foundation, once that is done, then it should be pretty easy to setup, but we're blocked on that.

**Comment by dylans** [comment]
Domain transfer in progress, the DNS will then be switched to CloudFlare, relevant host records added, universal SSL enabled, and then a rule to direct all traffic to https and then we should be set.

**Comment by dylans** [comment]
This should be all taken care of. Please let me know if you see any issues.

**Comment by agubler** [comment]
> Should perhaps also auto forward from http to https once sorted.

Think this would still be good

**Comment by dylans** [comment]
Should be enabled now as well (may require clearing the cache).

**Comment by kitsonk** [comment]
This is resolved.

**Comment by kitsonk** [comment]
These tend to be provided by the hosting provider.  Because we [moved to CloudFlare](https://github.com/dojo/dojo.io/issues/24#issuecomment-300178674) and the configuration with our hosting provider ensured we could do this.
