### ISSUE TITLE
Tutorial feedback - Deploying to production

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#240]
Link: https://dojo.io/tutorials/006_deploying_to_production/#5

Step 5: Links in the "Next steps" section all link to a coming soon page.

**Comment by kitsonk** [comment]
Refs #107

We should ensure we have an issue in dojo/dojo.io for the creation of content we link to.

Ideally we would add a comment to the `.md` referencing the the issue number:

```md
<!-- TODO: https//github.com/dojo/dojo.io/issues/999 -->
```
