### ISSUE TITLE
Tutorial Development Environment - various minor improvements

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#244]
https://dojo.io/tutorials/1050_development_environment/#2

Adding a number of feedbacks to this ticket since they are all part of the same 'step' in the tutorial:

__Feedback 1__ (Done ✅)

Step 2: “ In WorkerContainer, there should be code ”

“There should” -> “there is”

__Feedback 2__

Step 2: “To configure tasks:”

Better to use an ordered list here (is currently unordered).

__Feedback 3__

Step 2: “Press ⌘⇧P/Ctrl⇧P to open the command list.”

Spacing and plus symbol separators would be better here e.g. “Press ⌘ + ⇧ + P / Ctrl + ⇧ + P”

__Feedback 4__

Step 2: “Start typing tasks and select the command Tasks: Configure Task Runner”

When I select the specified option, I am prompted with additional options. Maybe this changed in a recent version of VS Code, might be useful to update the tutorial so it mentions to select “Others” as the third step.

![image](https://user-images.githubusercontent.com/381495/31780604-1618edde-b4ee-11e7-90d1-b6d54e453f4b.png)

__Feedback 5__

Step 2: “so consider the following code to configure it within tasks.json:”

Better to write this as an instruction: “Replace your current tasks.json file with the code below:”

__Feedback 6__

Step 2: “so consider the following code to configure it within tasks.json:”

Needs additional commentary on what the config does. How does it help the user, parts to pay attention to etc.

__Feedback 7__

Step 2: “Once configured, those tasks will be available in the IDE along with build”

There’s already a screenshot which is useful, but would also add a text based alternative to explain how the tasks are available in the IDE. e.g.
1) open command palette
2) type in task
3) hit enter
4) observe….<explain here what should happen based on the config the user entered)

![image](https://user-images.githubusercontent.com/381495/31780670-50e7fe0a-b4ee-11e7-83b8-1cc63f296f2e.png)

**Comment by kitsonk** [comment]
All of these make sense.
