### ISSUE TITLE
Dojo 2 tutorial URL structure

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#248]
Came out of some tutorial feedback I was doing:

URLs look like this: https://dojo.io/tutorials/002_creating_an_application/#1

Hyphens are however cleaner for URLs.

Also not a big deal at all, but the "002" looks odd, is it needed? Could the URL just be something like: tutorial/creating-an-application ?

**Comment by kitsonk** [comment]
> Hyphens are however cleaner for URLs.

How so?

> Also not a big deal at all, but the "002" looks odd, is it needed? Could the URL just be something like: tutorial/creating-an-application ?

We would have to create some other meta data file to order the tutorials.  It felt easiest to maintain to include the ordering explicitly the tutorial path.

**Comment by umaar** [comment]
> How so?

Actually good call, I guess what I really meant is: hyphens look more natural to me personally. But putting aside my personal prefs, they are recommended for SEO: https://support.google.com/webmasters/answer/76329?hl=en
