### ISSUE TITLE
Tutorial feedback - Project files

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#261]
General note: After a while of going through the tutorials, the downloaded files become a little messy e.g.

![image](https://user-images.githubusercontent.com/381495/31816356-e41548ba-b587-11e7-8721-1bfed1ae539a.png)

I think it’d be better to put all demos into one repo so as people are going through tutorials, all they have to do is:

1. Checkout a single repo (if they haven’t already)
2. Navigate to the relevant folder

**Comment by dylans** [comment]
This was definitely part of the original plan, but something we deferred until later as we weren't sure how all of this would end up and what would be easiest, etc.

**Comment by kitsonk** [comment]
Closing in favour of dojo/meta#139
