### ISSUE TITLE
Tutorial feedback - Working with the Registry

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#295]
Feedback for this tutorial: https://dojo.io/tutorials/1020_registries/

---

[x] __Feedback 1__

Step 1: “Registries everywhere”

Routing links to a coming soon page.

---

[ ] __Feedback 2__

Step 3: “Update the _renderBack function to use the WorkerBack registry items in Worker.ts”

![image](https://user-images.githubusercontent.com/381495/31833329-232aba50-b5c2-11e7-87eb-25597fb99d07.png)

I think it would be useful to get some linting going on, and beautifying this code a bit more, e.g. one variable per line.

---

[ ] __Feedback 3__

Step 3: “Now define a function that lazily loads WorkerBack.ts in the registry”

![image](https://user-images.githubusercontent.com/381495/31833352-32378c44-b5c2-11e7-8bf4-b7150e3d1f39.png)

To align with the web platform, could this use JavaScript ESM dynamic imports instead?

---

[ ] __ Feedback 4__

Step 3: “Use Before You Define The registry is designed to mirror the behavior and API of custom elements wherever possible”

Is “custom elements” referring to web components? Would be good to add some clarification on that.

---

[x] __Feedback 5__

Step 3: “defined, an used before it is defined and”

Typo with “an”.

---

[x] __Feedback 6__

Step 3: “One neat feature is that a registry item can be used before it is defined, and, once defined, an used before it is defined and, once defined, widgets that use the registry will automatically re-render!”

This section is confusing to read and can be reworded.

---

[x] __Feedback 7__

Step 3: “Auto Bundling Support”

The link to “build command tutorial.” links to a coming soon page.

**Comment by matt-gadd** [comment]
@umaar I think at the point when this tutorial was written **Feedback 3** wasn't supported as TypeScript couldn't down emit `import()`, but now that way is recommended (and the method in the tutorial is now considered deprecated).

**Comment by agubler** [comment]
@umaar with regards to **Feedback 2** I think generally we should use prettier (or equivalent) across all the demos, because although this tutorial touched the function it didn't create it. So we should address formatting, code style for all demo files.

**Comment by maier49** [comment]
It looks like all this feedback has been addressed, with the exception of Feedback 4 RE: custom elements. But the text is specifically mentioning the custom elements API which is in my mind clearer than mentioning Web Components in general..
