### ISSUE TITLE
Tutorial Creating Widgets#7 - worker array define error 

### ISSUE THREAD

**Issue by xiaohulu** [dojo/dojo.io#307]
copy below code to VS Code, dispaly error. Did I miss something?

![error_array_dojo_io](https://user-images.githubusercontent.com/624517/32313747-5bdddc70-bfdf-11e7-95e3-2ea4b1f5ebc1.png)

![error_array_vscode](https://user-images.githubusercontent.com/624517/32313748-5c10cb26-bfdf-11e7-88fb-70f0c9baf16d.png)

**Comment by kitsonk** [comment]
@xiaohulu yes that should just be: `const workers = [ ... ]`

Thanks for the bug report!
