### ISSUE TITLE
Allow code snippets to be included in .md files

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#31]
Currently there are several places in the dojo.io source where code snippets are manually copied from demo files into markdown files. Ideally, the markdown files should be able to link directly to the code snippets so that they don't get out of sync.

**Comment by dylans** [comment]
I believe this was addressed with https://github.com/dojo/dojo.io/pull/42/ ?

**Comment by vansimke** [comment]
Yes, this has been addressed
