### ISSUE TITLE
Cookbook recipe: Create a new Dojo 2 app (Command Line and building)

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#313]
- Demonstrate the minimal amount of code necessary to get it working
- Exclude boilerplate code which adds too much noise
- Include links to tutorials, source code and GitHub projects where appropriate
- Don't be overly verbose
- Make it easy for the user to copy and paste code without having to understand architectural concepts related to Dojo 2
- Address common use cases from the community
- Make sure code snippets do not become a maintenance burden as Dojo 2 evolves

There is a separate issue for creating the guidelines, so keep that in mind as you draft this first recipe.

**Comment by dylans** [comment]
Closed in #316.
