### ISSUE TITLE
Cookbook recipes: Three widget recipes

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#315]
- Demonstrate the minimal amount of code necessary to get it working
- Exclude boilerplate code which adds too much noise
- Include links to tutorials, source code and GitHub projects where appropriate
- Don't be overly verbose
- Make it easy for the user to copy and paste code without having to understand architectural concepts related to Dojo 2
- Address common use cases from the community
- Make sure code snippets do not become a maintenance burden as Dojo 2 evolves

There is a separate issue for creating the guidelines, so keep that in mind as you draft this first recipe.

_Edit_: [UH] - As these are quite small, bundling 3 recipes here:

- Render an array of items as a list
- Trigger a re-render of a widget 
- Render a built-in Dojo 2 widget

**Comment by umaar** [comment]
Sorry didn't realise this was assigned to you @vansimke - if you don't mind I already started this one, but no worries if you also already started, we can use your version!

**Comment by vansimke** [comment]
@umaar I haven't started on it yet, so have at it!
