### ISSUE TITLE
Add `hexo clean` to deployment scripts

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo.io#328]
Currently when we delete content fully from the site, the deployment script does not delete it, therefore we need to run `hexo clean` before we do the `hexo generate` to remove any deleted content from the site.

**Comment by vansimke** [comment]
I think this was already included in [PR 302](https://github.com/dojo/dojo.io/pull/302). Is there more to do here?

**Comment by kitsonk** [comment]
Fixed via #302
