### ISSUE TITLE
Improve `Injector` usage in State Management tutorial

### ISSUE THREAD

**Issue by mwistrand** [dojo/dojo.io#333]
In the [_State Management_](https://dojo.io/tutorials/1010_containers_and_injecting_state/) tutorial, the `Injector` from `@dojo/widget-core/Injector` is extended and its `get` method overridden to return `this`. However, this conflates state and injection, and should be redone to separate those two concerns.

**Comment by agubler** [comment]
This has been covered in the updates for the new injector API #419
