### ISSUE TITLE
Review and improve experience on mobile

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#340]
Review site functionality on mobile devices and address issues with visuals, performance, etc.

**Comment by dylans** [comment]
Scrolling on the iPhone is very slow... about 1/5th the normal rate of scrolling.

**Comment by matt-gadd** [comment]
the tutorial ux on mobile:

* giant footer that takes up a lot of the screen space (next/prev page and page numbers)
* footer cuts off content
* whitespace around tutorial breadcrumb takes up a large amount of space
* the page buttons hard to press

Overall you end up having to scroll so much to see very little content which is frustrating. 

Can we do away with pages all together on mobile and just have 1 large continuous piece of content?

**Comment by vansimke** [comment]
* remove outer-most scroll bar on all pages (this is not a mobile issue)

**Comment by vansimke** [comment]
Resolved by #342
