### ISSUE TITLE
Allow closing of Plunkr Panel

### ISSUE THREAD

**Issue by gavinr** [dojo/dojo.io#35]
If I'm working on the tutorials locally (not using Plunkr), I do not want to see the Plunkr panel and it takes up a lot of room on the screen. Would be nice to allow that panel to be minimized.

**Comment by dylans** [comment]
Agreed Gavin, we were discussing this on Friday as well...

**Comment by devpaul** [comment]
We've removed Plunker from the site and will reevaluate in #61
