### ISSUE TITLE
Update usage of `Injector` for stores tutorial to demonstrate the recommended practice

### ISSUE THREAD

**Issue by agubler** [dojo/dojo.io#362]
Currently the tutorial creates an class for the external state that extends `Injector` and is registered directly in the `registry`. This should be updated to be decoupled from the `Injector` and passed as the `payload` in the `Injector`s constructor.

**Comment by dylans** [comment]
As part of this update, we should perhaps take a moment to explain how we don't use reducers and why we find that to be better than the typical Redux reducer pattern for some use cases.

**Comment by agubler** [comment]
this has been updated with the new registry injector API
