### ISSUE TITLE
Tutorials for widget creation

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#37]
Consider adding one (or more) tutorials that help new users understand the nuances of authoring non-trivial widgets.

**Comment by vansimke** [comment]
This should cover widget and property lifecycle, state injection, as well as packaging widgets as web components. If that is too much content for one tutorial, we should break this into multiple tutorials that are scoped more appropriately.

**Comment by kitsonk** [comment]
I think we should think of a use case, and build the tutorial around that.

For example, a common use case, which was common in Dojo 1, would be something like:

> As a developer, I need to create a drop down list text box which gives and incremental lookup against a set of values that I am retrieving from a back end service.

There maybe other use cases that are better, but we should talk about the functionality we want to create a tutorial about versus a list of technical features.
