### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#380]
Have made a PR to make some improvements: https://github.com/dojo/dojo.io/pull/379

Some other notes which aren't included in that PR:

> If the finished directory of the tutorial should be built and tested as part of the CI build, it needs to

Would a finished tutorial ever _not_ be tested + built? If not, we could reword this, otherwise, could we specify in which case a finished tutorial may _not_ need to be built + tested?

> You can build APIs for a specific project by selecting the appropriate configuration.

What is the "appropriate configuration"? Should specify

> When you want Travis to publish merge to your local master branch

Better wording here.

Just an FYI, at the bottom of the readme, there is a TODO under the title "Automated Deploy to Production".

**Comment by devpaul** [comment]
PR merged
