### ISSUE TITLE
Trouble running build command in tutorial 001 "Your first Dojo 2 application"

### ISSUE THREAD

**Issue by haakym** [dojo/dojo.io#387]
Hi! I am following this tutorial: https://dojo.io/tutorials/001_static_content/#1

After downloading the required files for the tutorial and getting to the root of the project I was unable to run the first command successfully `dojo build --mode dev --watch memory --serve`, which instead output the generic dojo help output:

```bash
λ dojo build --mode dev --watch memory --serve
dojo help

Usage: dojo <group> <command> [options]

Hey there, here are all the things you can do with @dojo/cli:

Commands:
  create   scaffolds a new app
  eject    disconnect your project from dojo cli commands
  init     create a .dojorc file
  version  provides version information for all installed commands and the cli
           itself

Options:
  -h, --help  Show help                                                [boolean]

For more information on any of these commands just run them with '-h'.

e.g. 'dojo build -h' will give you the help for the 'build' group of commands.

If a non-builtin command (e.g. build) appears missing from the command list,
please ensure it is listed in package.json and correctly installed.

Unknown arguments: mode, watch, serve, build
```

Following the instructions from the output, I checked package.json for the `build` command:

```json
{
  "name": "biz-e-corp",
  "version": "1.0.0",
  "scripts": {
    "test": "dojo build -m test && dojo test",
    "build": "dojo build"
  },
  "dependencies": {
    "@dojo/core": "~0.3.1",
    "@dojo/has": "~0.1.2",
    "@dojo/routing": "~0.4.1",
    "@dojo/shim": "~0.2.4",
    "@dojo/widget-core": "~0.6.1",
    "@dojo/i18n": "~0.4.1",
    "@dojo/widgets": "~0.4.1"
  },
  "devDependencies": {
    "@dojo/cli-build-app": "~0.1.0",
    "@dojo/cli-test-intern": "~0.4.0",
    "@dojo/loader": "~0.1.1",
    "@dojo/test-extras": "~0.4.1",
    "@types/glob": "~5.0.0",
    "@types/grunt": "~0.4.0",
    "@types/node": "^6.0.46",
    "@types/sinon": "^1.16.35",
    "intern": "~4.1.5",
    "sinon": "^2.0.0",
    "typescript": "~2.6.1"
  }
}
```

... and assumed I'd have to `npm install` which then allowed the `build` command to be run successfully.

So I'd like to ask if the tutorial needs to be updated with instructions to run `npm install` or does the `build` command in package.json need to include some installation command or am I just doing something wrong? I'd be happy to submit a PR for this if the tutorial instructions need updating.

Thanks in advance!

**Comment by haakym** [comment]
Whoops, just realised the instructions for the `npm install` is in step 0 https://dojo.io/tutorials/001_static_content/#0 my bad!

**Comment by agubler** [comment]
Cool thanks!
