### ISSUE TITLE
Intermediate data format for API docs

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#39]
We need to build  an intermediate data format for API docs (i.e. JSON or markdown).  Goal is the ability to rebuild the site without checking out all of the repos.

**Comment by devpaul** [comment]
I have a preview of this functionality on [devpaul/dojo.io@typedoc-json](https://github.com/devpaul/dojo.io/tree/typedoc-json). 

I want to add the ability to limit the number of versions built using a filter function or string (e.g. latest, > 2.0.0.beta.1) so we don't always build all of the missing APIs all the way back to alpha.

After that, a little cleanup and this should be ready for review.

**Comment by kitsonk** [comment]
Pro Tip of the day [semver](https://www.npmjs.com/package/semver). 😁
