### ISSUE TITLE
Improve SEO of cookbook

### ISSUE THREAD

**Issue by umaar** [dojo/dojo.io#390]
Check out the SERP for the Dojo 2 cookbook:

![image](https://user-images.githubusercontent.com/381495/36898230-d492226c-1e11-11e8-8dea-acc78d69b7c7.png)

We can't always control what shows up, but we can at least attempt to improve it. My suggestions:

- Can we avoid the code appearing in the snippet?
- A better title order? E.g. `Cookbook: Widgets | Dojo` -> `Widgets: Coobook | Dojo`
- A better title? E.g. to recipe to access a raw DOM node with Dojo 2 is `Cookbook: Rendering | Dojo` but would ideally be: `Access a raw DOM node: Dojo 2 Cookbook recipe` (doesn't have to be exactly like that though, but I think it's better when the initial words of the title are specific)
- `ObjectiveThis` needs fixing
- The `meta:description` should not have code in it

**Comment by dylans** [comment]
Page titles I believe are determined in https://github.com/dojo/dojo.io/blob/master/site/themes/dojo/layout/_partial/head.ejs ... care to raise a PR to address these suggestions. Keep in mind we want to follow the general guideline of 64 characters or less.

For ObjectiveThis and meta:description (and some of the other open graph data), I think it originates from https://github.com/dojo/dojo.io/blob/master/site/themes/dojo/layout/_partial/head.ejs#L33 , so we need to look into what is getting passed into hexo's open_graph setup ( https://hexo.io/docs/helpers.html#open-graph )... so in this head.js file, we need to inspect and refine the objective and title to make some of these changes.
