### ISSUE TITLE
Tutorial: Responding to events #1 console log problem

### ISSUE THREAD

**Issue by haakym** [dojo/dojo.io#403]
Hi

I am following the [Responding to Events tutorial](https://dojo.io/tutorials/004_user_interactions/) and in [step #1 ](https://dojo.io/tutorials/004_user_interactions/#1) an `onclick` event listener is registered on the `Worker` widget that is wired up to a `flip()` method that outputs some text to the console via `console.log()`.

Upon following the instructions to do the aforementioned and attempting to fire the event in the browser I found that no text is output to the console, however, when adding `alert()` to the `flip()` method the window alert displays just fine in the browser when triggering the event, but there is still no sign of the text in the console.

I have on idea why this is happening (webpack/ts related perhaps?) and I realise this is a minor issue because the `console.log` eventually gets removed, but thought I'd flag this up as I spent a good 10 mins thinking I'd done something wrong and that I'd registered the event listener incorrectly.

If anyone is interested in investigating this issue I've got a commit here which has the setup where it failed for me: https://github.com/haakym/dojo-tuts/commit/ad0d4314caa7160e9fbb825630966de5a9c774cd

Thanks!

**Comment by agubler** [comment]
Hey @haakym I pulled your commit, ran `dojo build app -w -s` and using chrome flipping the cards seemed to correctly log `the flip method has been fired!` in the devtools console.

**Comment by haakym** [comment]
Thanks for your help @agubler. I have fixed it now, it was an issue with my Chrome settings, apologies!
