### ISSUE TITLE
Release dates

### ISSUE THREAD

**Issue by spaceone** [dojo/dojo.io#496]
Please write the date when the releases where published on https://download.dojotoolkit.org/.

**Comment by dylans** [comment]
@spaceone we generally track this at https://github.com/dojo/dojo/releases rather than something to manually duplicate on the Dojo website.

**Comment by dylans** [comment]
Note that this repo is for Dojo 2 and newer... the Dojo 1.x website is at https://github.com/dojo/dojo-website .

For release dates of 2.0 and newer, please visit https://github.com/dojo/framework/releases (and https://github.com/dojo/core/releases for 2.0).
