### ISSUE TITLE
Rename css modules in tutorials

### ISSUE THREAD

**Issue by rorticus** [dojo/dojo.io#5]
`grunt-dojo2` and `cli-build` were both updated to rename CSS modules as `.m.css` (instead of `.css`).

What this means for you!

* Any CSS file that is imported, i.e., `import * as styles from './styles/myfile.css'` needs to be renamed to `.m.css`, and the import statement updated: `import * as styles from './styles/myfile.m.css`.
* Other CSS files (`main.css`) do not need to be renamed.

**Comment by vansimke** [comment]
@rorticus The demo example in Plunker are working without this change. Can you review this issue and give more details about what changes should be made? At this point, everything appears to be working without any changes.

**Comment by rorticus** [comment]
@vansimke , I think the Plunkr demo is still working because it doesn't use the CSS module creation offered by `grunt-dojo2` and `cli-build`. Since everything was created manually, technically, there are no changes *required* by the tutorials, but I think that the best-practice is now that modules have the `.m.css` extension.

I believe the only change you need to make is to rename any **imported CSS file** to have a `.m.css` in it instead of `.css`.

Given the following,

```typescript
import * as styles from '/path/to/styles/my.css';
```

We would:

* Rename `my.css` to `my.m.css`
* Rename `my.css.js` to `my.m.css.js`
* Change the import to import `my.m.css`

I've created an overview of what happens to CSS files during the `grunt-dojo` build process, perhaps it would be helpful? In the tutorials we want to have similar steps preformed, but they are manual steps.

![image](https://cloud.githubusercontent.com/assets/2008858/24607556/6e6ce738-1840-11e7-9cac-e0cd8f017560.png)
