### ISSUE TITLE
Investigate request limit

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#57]
There is a 100,000 request limit per month on github pages.  We should see if the limit can be updated.  This is also directly related to #25

**Comment by devpaul** [comment]
I did a little searching and from what I understand 100,000 hits are not hard limits and GitHub will reach out well in advance. It's mostly to ensure availability of its services. Do we have a reference regarding the 100,000 hits/month request limit?

**Comment by kitsonk** [comment]
Closing this as it does not appear to be an immediate concern.
