### ISSUE TITLE
Search UI for API docs is broken

### ISSUE THREAD

**Issue by morrinene** [dojo/dojo.io#62]
The search seems to work only if it lands on an exact entry you select, but it doesn’t offer up partial matches.   As an example, if you type “iteration” it matches nothing and doesn’t even try to provide results.  if you type “has” it drops down results to click on, but doesn’t refresh the page with results.

**Comment by dylans** [comment]
The other issue I noticed is the results often take you to a 404... for example, search for then, which gives you http://dojo.io/api/core/v2.0.0-alpha.26//interfaces/thenable.html#then ... click on it and you end up on a 404... note also that these should probably be rebuilt for beta1...

**Comment by kitsonk** [comment]
The whole of the API docs might not work for us, we need to re-evaluate this.

**Comment by dylans** [comment]
Closing this as we have a different TypeDoc approach being followed.
