### ISSUE TITLE
Improved TypeDoc formatting

### ISSUE THREAD

**Issue by dylans** [dojo/dojo.io#65]
I had some similar thoughts to @jason0x43 when looking at the Dojo API docs that he mentioned in https://github.com/theintern/intern/issues/727#issuecomment-293028589

>TypeDoc runs on Intern, Leadfoot, and Dig Dug. Unfortunately, the generated output isn't super well organizaed. Ideally we'd have something that looks structurally similar to Leadfoot's and Dig Dug's API docs now (not necessarily with the same styles; the bootstrap-like aesthetic of the default TypeDoc docs is probably fine), with top level modules in a side bar, and without a lot of noise in the property and function lists.

> A stretch goal would be to improve TypeDoc's ability to handle arbitrary markdown files (besides README) so that we could just use TypeDoc to generate the entire docset for a given tool (expository docs as well as API docs).

Note that I'm not saying we need the left side navigation, but in general there's a lot of noise in the docs that make them less efficient to parse and use, and quite a bit of duplication of information in places.

A few points that I may have made elsewhere:

* Why are things called Globals when they're not
* Inside each package we repeat the package name 3 times at the top of the page (e.g. see the top of http://dojo.io/api/core/v2.0.0-alpha.26/ )
* I'd probably like to see usage first (e.g. the constructor)
* It would probably help for an index page to show all of the top level constructors, and then have a will to drill down and see more details, instead of having to click into every global to get details... e.g. the index page should list all the constructors for all the globals perhaps?

**Comment by kitsonk** [comment]
@agubler mentioned and I agree that I doubt that TypeDoc is going to work for Dojo 2.  There are just too many issues with it for it to be useful.  Honestly, we should remove the API docs for the time being.  They are totally useless at the moment.

**Comment by kitsonk** [comment]
Re-opening to reference #350

**Comment by dylans** [comment]
Closing this as we have a different TypeDoc approach being followed.
