### ISSUE TITLE
Update default API docs to beta1

### ISSUE THREAD

**Issue by dylans** [dojo/dojo.io#66]
Current API docs are for various versions of alpha, is this intentional?

**Comment by devpaul** [comment]
Yes. 

dojo.io is set to build the latest released API: https://github.com/dojo/dojo.io/blob/e806ad30a5b866b76352b5f75966628b08bee48c/support/grunt/config.ts#L44

When the latest is an alpha version it should be building those APIs. Is there a reason we'd want to change this behavior?

**Comment by devpaul** [comment]
This is issue likely related to a bug selecting the correct release that has since been resolved. I am closing this issue, but please feel free to reopen if further discussion is needed.
