### ISSUE TITLE
API docs for cli packages

### ISSUE THREAD

**Issue by dylans** [dojo/dojo.io#67]
Should API docs be generated for the various cli packages? It seems a bit odd given that the usage isn't to really use the code, but instead the generated API.

For example, is http://dojo.io/api/cli-build/v2.0.0-alpha.17/ useful, or should we instead be finding a way to show how to use the parts of the API intended for end users?

**Comment by devpaul** [comment]
We've removed the cli plugins from the api build configuration. Even if these APIs are useful they don't belong front-and-center on the API page. I agree that documentation regarding how to use the CLI and how to extend it would be many times more useful.
