### ISSUE TITLE
Tutorial uses inline styles

### ISSUE THREAD

**Issue by smhigley** [dojo/dojo.io#75]
Since inline styles are considered an anti-pattern, should we remove them from the tutorials?

Used in `widgets/Banner.ts` here:
https://github.com/dojo/dojo.io/blob/master/site/source/tutorials/003_creating_widgets/demo/initial/biz-e-corp/src/widgets/Banner.ts#L8

**Comment by dylans** [comment]
My suggestion is yes... cc @rishson

**Comment by rishson** [comment]
Yup - that needs to change to use `title` rather than `styles`.

**Comment by vansimke** [comment]
I think this is a dupe of #51.

**Comment by vansimke** [comment]
Closed via #86
