### ISSUE TITLE
Default grunt task overwrites git configuration

### ISSUE THREAD

**Issue by vansimke** [dojo/dojo.io#98]
The README.md file states, in the Quick Start section, that the proper way to deploy the site locally includes, amongst other things, running the default `grunt` task. When this task is run, however, the  global git configuration file is changed. The `user.email` setting is overwritten to support@sitepen.com and a new `user.name` field is added with the value "Travis". These changes are not reverted when the `grunt` task is completed so the users configuration is left in a corrupted state.

**Comment by devpaul** [comment]
Moved to dojo/grunt-dojo2-extras#22
